<MenuScreen>
    name: 'menu'
    FloatLayout:
        FloatLayout:                
            size: root.width, root.height
            Image:
                source: 'menu_kadz_1.jpg'
                size: (1024,600)
                pos_hint: {'x':0,'y':0}
                #GRAFIKA: https://www.foghornbrewhouse.com.au/newcastle/craft-beer-brewhouse-brewery/

        GridLayout:
            #pos: (256,340)
            pos_hint: {'x':0.1,'y':0.42}
            size_hint: (.8,.25)
            cols: 4
            rows: 1
            spacing: 5

            Button:       
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 36
                text: 'ZACIERANIE'
                on_press: root.go_to_zacieranie()
                #on_press: root.manager.current = 'zacieranie'
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 36
                text: 'WARZENIE'
                on_press: root.go_to_warzenie()
                #on_press: root.manager.current = 'warzenie'
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 36
                text: 'WAGA'
                on_press: root.manager.current = 'waga'
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 36
                text: 'PRZEPISY'
                on_press: root.manager.current = 'przepisy'
                background_color: (71/255,71/255,69/255,1)
                
<ZacieranieScreen>
    name: 'zacieranie'
    temp_zadana: temp_zadana
    ilosc_slodu: ilosc_slodu
    
    FloatLayout:
        FloatLayout:
            size: root.width, root.height

            Image:
                source: 'Logo_male_tlo_czarne.jpg'
                size: .2,.1
                pos_hint: {'x':-.35,'y':-.42}
            
            Button:
                size_hint: (0.25, 0.1)
                pos: (10,530)
                font_name:"Impacted"
                font_size: 36
                text: 'menu'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.manager.current = 'menu'
                
            Button:
                size_hint: (0.25, 0.1)
                pos: (495,530)
                font_name:"Impacted"
                font_size: 32
                text: 'ZACIERANIE START'
                background_color: (47/255,204/255,12/255,1)
                on_press: root.start_zacieranie()

            Button:
                size_hint: (0.25, 0.1)
                pos: (755,530)
                font_name:"Impacted"
                font_size: 32
                text: 'ZACIERANIE STOP'
                background_color: (255/255,0/255,0/255,1)
                on_press: root.stop_zacieranie()
            
            Button:
                size_hint: (0.3, 0.1)
                pos_hint: {'x':.69,'y':.12}
                font_name:"Impacted"
                font_size: 36
                text: root.dane_state
                background_color: (71/255,71/255,69/255,1)
                #on_press: root.manager.current = 'wykres'
                on_press: root.zbieraj_dane()

            Button:
                size_hint: (0.25, 0.1)
                pos_hint: {'x':.39,'y':.12}
                font_name:"Impacted"
                font_size: 36
                text: 'Tarowanie'
                background_color: (71/255,71/255,69/255,1)
                #on_press: root.manager.current = 'wykres'
                on_press: root.tarowanie()

        GridLayout:
            pos: (450,300)
            size_hint: (.5,.3)
            cols: 3
            rows: 3
        
            Label:
                text: "Temp. Zadana (wpisz) :"
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1.5,1)
                background_color: (71/255,71/255,69/255,1)
            Label:
                text: ""
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1,1)
                background_color: (0,0,0,1)

            TextInput:
                id: temp_zadana
                text: "0"
                halign: 'center'
                font_name:"Digital"
                font_size: 55
                size_hint: (1,1)
                multiline: False
                #background_color: (71/255,71/255,69/255,1)
                background_color: (0/255,0/255,0/255,1)
                foreground_color: [1,1,1,1]
                on_focus: root.text_focused()
            Label:
                text: "temp. Aktualna :"
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1.5,1)
                background_color: (71/255,71/255,69/255,1)
            Label:
                text: ""
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1,1)
                background_color: (0,0,0,1)
            Label:
                id: temp_akt
                text: root.temp_akt
                halign: 'left'
                font_name:"Digital"
                font_size: 55
                size_hint: (1,1)
                background_color: (0,0,0,1)
            Label:
                text: "Waga aktualna :"
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1.5,1)
                background_color: (71/255,71/255,69/255,1)
            Label:
                text: ""
                halign: 'left'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1,1)
                background_color: (0,0,0,1)
            Label:
                id: waga_akt
                text: root.waga_akt
                halign: 'left'
                font_name:"Digital"
                font_size: 55
                size_hint: (1,1)
                background_color: (0,0,0,1)

        GridLayout:
            pos_hint: {'x':.55,'y':-.05}
            size_hint: (.4,.2)
            cols: 1
            rows: 1
            Label:
                id: zegar
                text: root.zegar
                font_name:"Digital"
                halign: 'right'
                font_size: 50
                size_hint: (.5,1)

#KALKULATOR ILOSCI WODY
        GridLayout:
            pos_hint: {'x':.01,'y':.3}
            size_hint: (.35,.46)
            cols: 1
            rows: 5

            Label:
                text: "Kalkulator ilosci wody :"
                halign: 'left'
                font_name:"Impacted"
                text_size: self.size
                font_size: 32
                size_hint: (1,1)
                color: 0,138/255,0,1
                background_color: (71/255,71/255,69/255,1)
            Label:
                text: "ilosc slodu [kg] :"
                text_size: self.size
                halign: 'left'
                valign: 'bottom'
                font_name:"Impacted"
                font_size: 32
                size_hint: (1,1)
                color: 0,138/255,0,1
                background_color: (71/255,71/255,69/255,1)

            TextInput:
                id: ilosc_slodu
                text: "0"
                halign: 'center'
                valign: 'top'
                font_name:"Impacted"
                font_size: 38
                size_hint: (1,1)
                multiline: False
                background_color: (0/255,0/255,0/255,1)
                foreground_color: [0,1,0,1]
                on_focus: root.text_focused()
            Label:
                text: "Ilosc wody [L] :"
                text_size: self.size
                halign: 'left'
                valign: 'bottom'
                font_name:"Impacted"
                color: 0,138/255,0,1
                font_size: 32
                size_hint: (1,1)
                background_color: (71/255,71/255,69/255,1)
            Label:
                id: ilosc_wody
                text: root.ilosc_wody
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                font_name:"Impacted"
                color: 0,138/255,0,1
                font_size: 38
                size_hint: (1,1)
                background_color: (71/255,71/255,69/255,1)


        GridLayout:
            pos_hint: {'x':.5,'y':.3}
            size_hint: (.4,.2)
            cols: 1
            rows: 2
        
            Label:
                text: "AKTUALNY KROK ZACIERANIA (wg. temp) :"
                halign: 'left'
                font_name:"Impacted"
                font_size: 30
                size_hint: (1,1)
                background_color: (71/255,71/255,69/255,1)
            Label:
                id: krok_zacierania
                text: root.krok_zacierania
                font_name:"Impacted"
                halign: 'left'
                font_size: 36
                size_hint: (1,1)
                background_color: (71/255,71/255,69/255,1)

            
        
<WarzenieScreen>
    name: 'warzenie'
    czas_stoper: czas_stoper
    
    FloatLayout:
        FloatLayout:
            size: root.width, root.height
            
            Button:
                size_hint: (0.25, 0.1)
                pos: (10,530)
                font_name:"Impacted"
                font_size: 36
                text: 'menu'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.manager.current = 'menu'
            Button:
                size_hint: (0.25, 0.1)
                pos: (495,530)
                font_name:"Impacted"
                font_size: 32
                text: 'Warzenie START'
                background_color: (47/255,204/255,12/255,1)
                on_press: root.start_warzenie()

            Button:
                size_hint: (0.25, 0.1)
                pos: (755,530)
                font_name:"Impacted"
                font_size: 32
                text: 'Warzenie STOP'
                background_color: (255/255,0/255,0/255,1)
                on_press: root.stop_warzenie()

            Label:
                text: "Ustaw moc grzania [%]:"
                font_name:"Impacted"
                halign: 'left'
                font_size: 30
                size_hint: (.3,.1)
                pos_hint: {'x':.5,'y':.75}

            #Button:
                #size_hint: (0.3, 0.1)
                #pos_hint: {'x':.69,'y':.12}
                #font_name:"Impacted"
                #font_size: 36
                #text: 'wykres temp.'
                #background_color: (71/255,71/255,69/255,1)
                #on_press: root.manager.current = 'wykres'

            Button:
                size_hint: (0.3, 0.1)
                pos_hint: {'x':.69,'y':.12}
                font_name:"Impacted"
                font_size: 36
                text: root.dane_state
                background_color: (71/255,71/255,69/255,1)
                #on_press: root.manager.current = 'wykres'
                on_press: root.zbieraj_dane()

            Image:
                source: 'Logo_male_tlo_czarne.jpg'
                size: (100,50)
                pos_hint: {'x':-.35,'y':-.42}

            Slider:
                id: slider
                min: 0
                max: 100
                step: 1
                value_track: True
                value_track_color: (0,1,0,1)
                orientation: 'horizontal'
                pos_hint: {'x':.45,'y':.6}
                size_hint: (.5,.2)
                on_value: moc_zad.text = str(int(self.value))
                on_touch_up: root.slider_moc(moc_zad.text)
            
            #STOPER
            Label:
                text: "STOPER"
                font_name:"Impacted"
                text_size: self.size
                halign: 'center'
                valign: 'middle'
                color: 0,138/255,0,1
                font_size: 44
                size_hint: (.4,.12)
                pos_hint: {'x':.01,'y':.7}
                canvas.before:
                    Color:
                        rgba: 0/255,0/255,0/255,1
                    Rectangle:
                        size: self.size
                        pos: self.pos
            Label:
                id: stoper
                text: root.stoper
                font_name:"Impacted"
                text_size: self.size
                halign: 'center'
                font_size: 110
                size_hint: (.4,.2)
                pos_hint: {'x':.01,'y':.4}
        GridLayout:
            pos_hint: {'x':.01,'y':.62}
            size_hint: (.4,.08)
            cols: 3
            rows: 1
            spacing: 5

            Label:
                text: "Czas :"
                font_name:"Impacted"
                text_size: self.size
                halign: 'right'
                valign: 'bottom'
                font_size: 32
                size_hint: (.7,1)
            TextInput:
                id: czas_stoper
                text: "60"
                text_size: self.size
                halign: 'center'
                valign: 'top'
                font_name:"Impacted"
                font_size: 32
                size_hint: (.3,1)
                multiline: False
                background_color: (71/255,71/255,69/255,0.5)
                foreground_color: [1,1,1,1]
                on_focus: root.text_focused()
            Label:
                text: "min"
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'bottom'
                font_size: 32
                size_hint: (.7,1)
        GridLayout:
            pos_hint: {'x':.01,'y':.25}
            size_hint: (.4,.1)
            cols: 3
            rows: 1
            spacing: 5

            Button:
                size_hint: (1, 1)
                pos: (755,530)
                font_name:"Impacted"
                font_size: 32
                text: 'start'
                background_color: (0/255,255/255,0/255,1)
                on_press: root.stoper_start()
            Button:
                size_hint: (1, 1)
                pos: (755,530)
                font_name:"Impacted"
                font_size: 32
                text: 'stop'
                background_color: (255/255,0/255,0/255,1)
                on_press: root.stoper_stop()
            Button:
                size_hint: (1, 1)
                pos: (755,530)
                font_name:"Impacted"
                font_size: 32
                text: 'zeruj'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.stoper_zeruj()

            
        GridLayout:
            pos_hint: {'x':.5,'y':.35}
            size_hint: (.4,.3)
            cols: 2
            rows: 3
            Label:
                text: "USTAWIONA MOC:"
                font_name:"Impacted"
                halign: 'left'
                font_size: 30
                size_hint: (1.5,1)
            Label:
                id: moc_zad
                text: '0'
                font_name:"Digital"
                halign: 'right'
                font_size: 55
                size_hint: (.5,1)
            Label:
                text: "Aktualna MOC:"
                font_name:"Impacted"
                halign: 'left'
                font_size: 30
                size_hint: (1.5,1)
            Label:
                id: moc_akt
                text: '0'
                font_name:"Digital"
                halign: 'right'
                font_size: 55
                size_hint: (.5,1)
            Label:
                text: "Temp. Aktualna:"
                font_name:"Impacted"
                halign: 'left'
                font_size: 30
                size_hint: (1.5,1)
            Label:
                id: akt_temp
                text: root.akt_temp
                font_name:"Digital"
                halign: 'right'
                font_size: 55
                size_hint: (.5,1)
        
        GridLayout:
            pos_hint: {'x':.55,'y':-.05}
            size_hint: (.4,.2)
            cols: 1
            rows: 1
            Label:
                id: zegar
                text: root.zegar
                font_name:"Digital"
                halign: 'right'
                font_size: 50
                size_hint: (.5,1)
                
<WagaScreen>
    name: 'waga'
    FloatLayout:
        FloatLayout:
            size: root.width, root.height
            
            Button:
                size_hint: (0.25, 0.1)
                pos: (10,530)
                font_name:"Impacted"
                font_size: 36
                text: 'menu'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.manager.current = 'menu'

            Image:
                source: 'Logo_male_tlo_czarne.jpg'
                size: (100,50)
                pos_hint: {'x':-.35,'y':-.42}

            Button:
                size_hint: (0.25, 0.1)
                pos_hint: {'x':.39,'y':.22}
                font_name:"Impacted"
                font_size: 36
                text: 'Tarowanie'
                background_color: (71/255,71/255,69/255,1)
                #on_press: root.manager.current = 'wykres'
                on_press: root.tarowanie()

            Label:
                id: waga_akt
                text: root.waga_akt
                halign: 'left'
                font_name:"Digital"
                font_size: 200
                size_hint: (.6,.4)
                pos_hint: {'x':.2,'y':.4}
                background_color: (0,0,0,1)
            

<WykresTempScreen>
    name: 'wykres'
    FloatLayout:
        FloatLayout:
            size: root.width, root.height
            
            Button:
                size_hint: (0.25, 0.1)
                pos: (10,530)
                font_name:"Impacted"
                font_size: 36
                text: 'powrot'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.manager.current = 'warzenie'

<PrzepisyScreen>
    name: 'przepisy'
    FloatLayout:
        FloatLayout:
            size: root.width, root.height

            Button:
                size_hint: (0.25, 0.1)
                pos: (10,530)
                font_name:"Impacted"
                font_size: 36
                text: 'menu'
                background_color: (71/255,71/255,69/255,1)
                on_press: root.go_to_menu()

            Image:
                source: 'Logo_male_tlo_czarne.jpg'
                size: (100,50)
                pos_hint: {'x':-.35,'y':-.42}
            
            Label:
                id: styl_piwa
                text: root.styl_piwa
                font_name:"Impacted"
                halign: 'right'
                font_size: 55
                size_hint: (.5,.1)
                pos_hint: {'x':.4,'y':.9}
            
            Label:
                text: 'Surowce (40L):'
                font_name:"Impacted"
                halign: 'left'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
                pos_hint: {'x':.3,'y':.74}
            Label:
                text: 'Zacieraniie :'
                font_name:"Impacted"
                halign: 'left'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
                pos_hint: {'x':.315,'y':.45}
            Label:
                text: 'Chmielenie :'
                font_name:"Impacted"
                halign: 'left'
                font_size: 28
                color: 0,138/255,0,root.visib
                size_hint: (.1,.1)
                pos_hint: {'x':.515,'y':.45}

        GridLayout:
            pos_hint: {'x':.28,'y':.55}
            size_hint: (.35,.2)
            cols: 1
            rows: 4

            Label:
                id: slod1
                text: root.slod1
                text_size: self.size
                font_name:"Impacted"
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: slod2
                text: root.slod2
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: slod3
                text: root.slod3
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: slod4
                text: root.slod4
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
        GridLayout:
            pos_hint: {'x':.5,'y':.265}
            size_hint: (.35,.2)
            cols: 1
            rows: 4

            Label:
                id: chmiel1
                text: root.chmiel1
                text_size: self.size
                font_name:"Impacted"
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 0,138/255,0,root.visib
                size_hint: (.1,.1)
            Label:
                id: chmiel2
                text: root.chmiel2
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 0,138/255,0,root.visib
                size_hint: (.1,.1)
            Label:
                id: chmiel3
                text: root.chmiel3
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 0,138/255,0,root.visib
                size_hint: (.1,.1)
            Label:
                id: chmiel4
                text: root.chmiel4
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 0,138/255,0,root.visib
                size_hint: (.1,.1)

        GridLayout:
            pos_hint: {'x':.28,'y':.26}
            size_hint: (.35,.2)
            cols: 1
            rows: 4

            Label:
                id: temp1
                text: root.temp1
                text_size: self.size
                font_name:"Impacted"
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: temp2
                text: root.temp2
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: temp3
                text: root.temp3
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
            Label:
                id: temp4
                text: root.temp4
                font_name:"Impacted"
                text_size: self.size
                halign: 'left'
                valign: 'middle'
                font_size: 28
                color: 194/255,130/255,12/255,root.visib
                size_hint: (.1,.1)
        
        GridLayout:
            pos_hint: {'x':.4,'y':.82}
            size_hint: (.5,.1)
            cols: 4
            rows: 1

            Label:
                text: "IBU"
                font_name:"Impacted"
                halign: 'right'
                font_size: 40
                color: 0,138/255,0,root.visib
                size_hint: (.5,.1)
            Label:
                id: ibu
                text: root.ibu
                font_name:"Impacted"
                halign: 'center'
                font_size: 40
                color: 0,138/255,0,root.visib
                size_hint: (.5,.1)
            Label:
                text: "BLG"
                font_name:"Impacted"
                halign: 'center'
                font_size: 40
                color: 222/255,81/255,0,root.visib
                size_hint: (.5,.1)
            Label:
                id: blg
                text: root.blg
                font_name:"Impacted"
                halign: 'center'
                font_size: 40
                color: 222/255,81/255,0,root.visib
                size_hint: (.5,.1)

        GridLayout:
            pos_hint: {'x':.01,'y':.25}
            size_hint: (.25,.6)
            cols: 1
            rows: 4

            spacing: 5

            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 24
                text: 'Schreibersdorf ALTBIER'
                on_press: root.schreibersdorf()
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 24
                text: 'Dziubrow IPA'
                on_press: root.ale()
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 24
                text: 'Dziubrow SUMMER ALE'
                on_press: root.summer_ale()
                background_color: (71/255,71/255,69/255,1)
            Button:
                size_hint: (.2, .2)
                font_name:"Impacted"
                font_size: 24
                text: 'Dziubrow DRY STOUT'
                on_press: root.stout()
                background_color: (71/255,71/255,69/255,1)